
const data ={
    products : [
      {
        id: 1,
        image: "https://m.media-amazon.com/images/I/61fy6IX+jTL._AC_SY100_.jpg",
        details: "Tata Sampann 100% Pure Premium Cashews Whole, 500g",
        brand: "Flavourful·500 g (Pack of 1)",
        rating: "2,544 ratings",
        price:585,
        prizestrike:"M.R.P: ₹1,340.00",
        discount:"(₹145.80/kg)",
        delivery: "Sat, January 21",
        buttontext: "Add to Cart",
        company:"by Tata Sampann"
      },
      {
        id: 2,
        image: "https://m.media-amazon.com/images/I/71lmddoIdNL._AC_SY100_.jpg",
        details: "Nuts About You RAISIN, 500 g | 100% Natural | Premium| Kishmish | Saugi",
        brand: "500 g (Pack of 1)",
        rating: "5,030 ratings",
        price:435,
        prizestrike:"M.R.P: ₹600.00",
        discount:"(₹28.80/100 g)",
        delivery: "Sat, January 21",
        buttontext: "Add to Cart",
        company:"by Florio"
      },
      {
        id: 3,
        image: "https://m.media-amazon.com/images/I/71PFaLxovsL._AC_SY100_.jpg",
        details: "DiSano Pure Honey 500 g (pack of 1)",
        brand: "Pure honeynatural & raw",
        rating: "3,742 ratings",
        price: 99,
        prizestrike:"M.R.P: ₹520.00",
        discount:"1offer from ₹99",
        delivery: "",
        buttontext: "See buying options",
        company:"by Disano"
      },
      {
        id: 4,
        image: "https://m.media-amazon.com/images/I/81U3UQ3IAaS._AC_SY100_.jpg",
        details: "Manna Millets 5Kg Combo Pack of 10 | Natural Grains | Unpolished Millets",
        brand: "White Rice",
        rating: "104 ratings",
        price: 699,
        prizestrike:"M.R.P: ₹1,300.00",
        discount:"(₹139.80/kg)",
        delivery: "Sat, January 21",
        buttontext: "Add to Cart",
        company:"by Manna"
      },
      {
        id: 5,
        image: "https://m.media-amazon.com/images/I/71m+M0SnDeL._AC_SY100_.jpg",
        details: "Nuts About You ALMONDS California, 500 g | New Crop 2022 | Premium ",
        brand: "Whole natural·500 g",
        rating: "3,140 ratings",
        price: 349.00,
        prizestrike:"M.R.P: ₹750.00",
        discount:"(₹69.80/100 g)",
        delivery: "Sat, January 21",
        buttontext: "Add to Cart",
        company:"by Happilo"
      },
      {
        id: 6,
        image: "https://m.media-amazon.com/images/I/81yERsPt4EL._AC_SY100_.jpg",
        details: "Nikunj Assam Tea, 1kgNikunj Assam Tea, 1kg",
        brand: "Assam·1 Count (Pack of 1)",
        rating: "390 ratings",
        price: 165.00,
        prizestrike:"M.R.P: ₹220.00",
        discount:"(₹165.00/count)",
        delivery: "Sat, January 21",
        buttontext: "Add to Cart",
        company:"by Nikunj"
      },
      {
        id: 7,
        image: "https://m.media-amazon.com/images/I/71hN-XjVwSL._AC_SY100_.jpg",
        details: "Happilo 100% Natural Californian Inshell Raw Walnut Kernels 500g Value Pack | Premium Akrot Giri | High in Protein & Iron | Low Calorie NutHappilo 100% Natural Californian Inshell Raw Walnu…",
        brand: "Walnut·500 g (Pack of 1)",
        rating: "ratings",
        price: 431.00,
        prizestrike:"M.R.P: ₹575.00",
        discount:"(₹86.20/100 g)",
        delivery: "Get it by Sat, January 21",
        buttontext: "Add to Cart",
        company:"by Happilo"
      },
    
      {
        id: 8,
        image: "https://m.media-amazon.com/images/I/61CLFkw3nQL._AC_SY100_.jpg",
        details: "Ferrero Rocher Moments, 12 Pieces (69.6 g)Ferrero Rocher Moments, 12 Pieces (69.6 g)",
        brand: "Praline·69.6 g (Pack of 1)",
        rating: "804 ratings",
        price: 154.00,
        prizestrike:"M.R.P: ₹199.00",
        discount:"(₹221.26/100 g)",
        delivery: "Get it by Sat, January 22",
        buttontext: "Add to Cart",
        company:"by Ferrero"
      },
      {
        id: 9,
        image: "https://m.media-amazon.com/images/I/61H2hPDyzsL._AC_SY100_.jpg",
        details: "NAMHYA PCOS PCOD Green Tea (with Shatavari, Ashoka) with Natural Ayurvedic Herbs for Hormonal Balance and Better Period Cycle NAMHYA PCOS PCOD Green Tea (with Shatavari, Ashoka) with Natural Ayurvedic Herbs for Hormonal Balance and Better Period Cycle 3.53 oz (100 Grams)NAMHYA PCOS PCOD Green Tea (with Shatavari, Ashoka)",
        brand: "Green·100 g (Pack of 1)",
        rating: "231 ratings",
        price: 522.00,
        prizestrike:"M.R.P: ₹599.00",
        discount:"(₹522.00/100 g)₹0.00 shipping",
        delivery: "",
        buttontext: "Add to Cart",
        company:"by NAMHYA"
      },
      {
        id: 10,
        image: "https://m.media-amazon.com/images/I/71Ye-tdw68L._AC_SY100_.jpg",
        details: "Cadbury Celebrations Premium Selections Chocolates Gift Pack, Assorted, 268 gCadbury Celebrations Premium Selections Chocolates Gift Packet",
        brand: "Chocolate·1 Count (Pack of 1)",
        rating: "9,902 ratings",
        price: 243.00,
        prizestrike:"M.R.P: ₹375.00",
        discount:"(₹90.67/100 g)",
        delivery: "Get it by Sun, January 22",
        buttontext: "See buying options",
        company:"by Cadbury"
      },
      {
        id: 11,
        image: "https://m.media-amazon.com/images/I/519nhEt5VeL._AC_SY100_.jpg",
        details: "Hershey's Kisses Everyday Moments Gift Pack 103.2gHershey's Kisses Everyday Moments Gift Pack 103.2g",
        brand: "Almond",
        rating: "142 ratings",
        price: 131.00,
        prizestrike:"M.R.P: ₹175.00",
        discount:"(₹126.94/100 g)",
        delivery: "Get it by Fri, January 20",
        buttontext: "Add to Cart",
        company:"by Hershey"
      },
      {
        id: 12,
        image: "https://m.media-amazon.com/images/I/71O1Jp3rgEL._AC_SY100_.jpg",
        details: "Pintola All Natural Peanut Butter (Crunchy) | Unsweetened | 30g Protein | Non GMO | Gluten Free | Vegan | Cholesterol Free (350g)Pintola All Natural Peanut Butter (Crunchy) | Unsweeten…",
        brand: "Crunchy",
        rating: "57,573 ratings",
        price: 150.00,
        prizestrike:"M.R.P: ₹165.00",
        discount:"(₹42.86/100 g)",
        delivery: "Get it by Sat, January 21",
        buttontext: "Add to Cart",
        company:"by Pintola"
      },
      {
        id: 13,
        image: "https://m.media-amazon.com/images/I/91CXDBEWyML._AC_SY100_.jpg",
        details: "JEENI MILLET HEALTH MIX millet and multi grains | All Natural Multigrain | Organic and Natural Product for 12 Year & Above Ag JEENI MILLET HEALTH MIX millet and multi grains | All Natural Multigrain | Organic and Natural Product for 12 Year & Above Age Pack of 1JEENI MILLET HEALTH MIX millet and multi grains | All N",
        brand: "1 Count (Pack of 1)",
        rating: "31 ratings",
        price: 396.00,
        prizestrike:"M.R.P: ₹220.00",
        discount:"(₹396.00/count)",
        delivery: "₹0.00 shipping",
        buttontext: "Add to Cart",
        company:"by EENI"
      },
      {
        id: 14,
        image: "https://m.media-amazon.com/images/I/71B5qacE2hS._AC_SY100_.jpg",
        details: "Happilo 100% Natural Californian Inshell Raw Walnut Kernels 500g Value Pack | Premium Akrot Giri | High in Protein & Iron | Low Calorie NutHappilo 100% Natural Californian Inshell Raw Walnu…",
        brand: "Walnut·500 g (Pack of 1)",
        rating: "ratings",
        price: 431.00,
        prizestrike:"M.R.P: ₹575.00",
        discount:"(₹86.20/100 g)",
        delivery: "Get it by Sat, January 21",
        buttontext: "Add to Cart",
        company:"by Nikunj"
      },
      {
        id: 15,
        image: "https://m.media-amazon.com/images/I/61HuMNoEUQL._AC_SY100_.jpg",
        details: "Nikunj Assam Tea, 1kgNikunj Assam Tea, 1kg",
        brand: "Assam·1 Count (Pack of 1)",
        rating: "390 ratings",
        price: 165.00,
        prizestrike:"M.R.P: ₹220.00",
        discount:"(₹165.00/count)",
        delivery: "Get it by Sat, January 21",
        buttontext: "Add to Cart",
        company:"by Cadbury"
      },
      {
        id: 16,
        image: "https://m.media-amazon.com/images/I/814iBcUf1aL._AC_SY100_.jpg",
        details: "Happilo 100% Natural Californian Inshell Raw Walnut Kernels 500g Value Pack | Premium Akrot Giri | High in Protein & Iron | Low Calorie NutHappilo 100% Natural Californian Inshell Raw Walnu…",
        brand: "Walnut·500 g (Pack of 1)",
        rating: "ratings",
        price: 431.00,
        prizestrike:"M.R.P: ₹575.00",
        discount:"(₹86.20/100 g)",
        delivery: "Get it by Sat, January 21",
        buttontext: "Add to Cart",
        company:"by Nikunj"
      },
      {
        id: 17,
        image: "https://m.media-amazon.com/images/I/51dWUMCgQzL._AC_SY100_.jpg",
        details: "Nikunj Assam Tea, 1kgNikunj Assam Tea, 1kg",
        brand: "Assam·1 Count (Pack of 1)",
        rating: "390 ratings",
        price: 165.00,
        prizestrike:"M.R.P: ₹220.00",
        discount:"(₹165.00/count)",
        delivery: "Get it by Sat, January 21",
        buttontext: "Add to Cart",
        company:"by Nikunj"
      },
      {
        id: 18,
        image: "https://m.media-amazon.com/images/I/71hN-XjVwSL._AC_SY100_.jpg",
        details: "Happilo 100% Natural Californian Inshell Raw Walnut Kernels 500g Value Pack | Premium Akrot Giri | High in Protein & Iron | Low Calorie NutHappilo 100% Natural Californian Inshell Raw Walnu…",
        brand: "Walnut·500 g (Pack of 1)",
        rating: "ratings",
        price: 431.00,
        prizestrike:"M.R.P: ₹575.00",
        discount:"(₹86.20/100 g)",
        delivery: "Get it by Sat, January 21",
        buttontext: "Add to Cart",
        company:"by Happilo"
      },
      {
        id: 19,
        image: "https://m.media-amazon.com/images/I/61fy6IX+jTL._AC_SY100_.jpg",
        details: "Nikunj Assam Tea, 1kgNikunj Assam Tea, 1kg",
        brand: "Assam·1 Count (Pack of 1)",
        rating: "390 ratings",
        price: 165.00,
        prizestrike:"M.R.P: ₹220.00",
        discount:"(₹165.00/count)",
        delivery: "Get it by Sat, January 21",
        buttontext: "Add to Cart",
        company:"by Nikunj"
      },
      {
        id: 20,
        image: "https://m.media-amazon.com/images/I/81a891BCbPL._AC_SY100_.jpg",
        details: "Happilo 100% Natural Californian Inshell Raw Walnut Kernels 500g Value Pack | Premium Akrot Giri | High in Protein & Iron | Low Calorie NutHappilo 100% Natural Californian Inshell Raw Walnu…",
        brand: "Walnut·500 g (Pack of 1)",
        rating: "ratings",
        price: 431.00,
        prizestrike:"M.R.P: ₹575.00",
        discount:"(₹86.20/100 g)",
        delivery: "Get it by Sat, January 21",
        buttontext: "Add to Cart",
        company:"by Happilo"
      }
    ]
}

export default data;

